version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./src/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
    networks:
      - prometheus-net
    restart: always

  watcher:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/app/src
    restart: unless-stopped

volumes:
  prometheus_data:

networks:
  prometheus-net: