version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
      - ./targets/targets.json:/etc/prometheus/targets.json
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
    networks:
      - prometheus-net
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - prometheus-net
    restart: always
    deploy:
      mode: global

  watcher:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./targets:/usr/src/app/targets/
      - ./src/ovr.xml:/usr/app/src/ovr.xml
    restart: unless-stopped

volumes:
  prometheus_data:

networks:
  prometheus-net: